import './globals.css';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import Sidebar from '@/components/layout/Sidebar';
import { Providers } from './providers';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn('dark font-sans antialiased', fontSans.variable)}>
        <Providers>
          <main role="main">
            <Sidebar />
            <section className="px-4 py-3 ml-[4.25rem]">{children}</section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
