import './globals.css';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import Header from '@/components/layout/Header';
import Sidebar from '@/components/layout/Sidebar';
import { Providers } from './providers';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const headerProps = {
  iconSize: 32,
  paddingX: 20,
  paddingY: 16,
};

const sidebarProps = {
  iconSize: headerProps.iconSize - 12,
  paddingX: headerProps.paddingX + 12 / 2,
};

const offsetX = 2 * sidebarProps.paddingX + sidebarProps.iconSize + 1;
const offsetY = 2 * headerProps.paddingY + headerProps.iconSize + 1;

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn('dark font-sans antialiased', fontSans.variable)}>
        <Providers>
          <Header {...headerProps} />
          <main role="main">
            <Sidebar
              {...sidebarProps}
              offset={offsetY}
            />
            <section
              style={{ marginLeft: `${offsetX}px` }}
              className="px-4 py-3"
            >
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
